### ISSUE TITLE
Suggest to install libiconv too.

### ISSUE THREAD

**Issue by gavenkoa** [kou1okada/apt-cyg#104]
Fresh Cygwin installation without `wget`:

```
bash# apt-cyg --help
You must install wget, tar and gawk to use apt-cyg.
```

I am adding a missing dependency and then attempt to install bash-completion:

```
bash# apt-cyg completion-install
Error: Required command [iconv] not found.
at : /home/user/.local/bin/apt-cyg: assert_command_exists: 84
```

Seems modern Cygwin comes only with `libiconv2`, which misses `iconv` utility...

In the README.md you already mention:

> apt-cyg requires the Cygwin default environment and the additional Cygwin packages:
> wget, ca-certificates, gnupg, libiconv

Please update the message of `apt-cyg --help` to include  `libiconv` (& gnupg ??) if you require them anyway...

**Comment by kou1okada** [comment]
Thanks for your suggestion.
How about the above change?

**Comment by gavenkoa** [comment]
Looks sound. Led to elimination of extra function - less is better ))
