### ISSUE TITLE
Error when install a package

### ISSUE THREAD

**Issue by thienhv** [kou1okada/apt-cyg#14]
I install nano with command 
$ apt-cyg install nano
And i had a error
gpgv: can't hash datafile: file open error
Error: BAD signature: setup.bz2.sig
Pls, help me. Thanks a lot.

**Comment by kou1okada** [comment]
Hmm,,, under 32 bit environment, gpgv seems not work correctly.
I changed backend of verify_signatures functon from gpgv to gpg.
Please update your apt-cyg to the latest version of this fork and try `apt-cyg install nano` again.

**Comment by thienhv** [comment]
Thanks a lot @kou1okada. It's working ok.
