### ISSUE TITLE
get_codepage returns invalid codepage

### ISSUE THREAD

**Issue by MAnantharaman** [kou1okada/apt-cyg#15]
I used the --use-setuprc option which calls cp2utf8 (why?) -> get_codepage. The current version of get_codepage on my Windwos XP SP3 system returns "CP850." (note the closing period) because chcp outputs "Aktive Codepage: 1252." I corrected the comman within get_codepage to ...
cmd.exe /c chcp |  sed 's/^.*: \([^.]*\).*$/\1/'
... and hope you can fix it the issue this way or another.

Regards, Martin

**Comment by kou1okada** [comment]
Now, I checked it on my Japanese version Windows XP Home Edition SP3 and Japanese version Windows 10 Pro Inside Preview Build 10074, and I get a result as below:

    >chcp 1252
    Active code page: 1252
    
    >chcp
    Active code page: 1252
    
    >powershell -Command [console]::OutputEncoding
    
    IsSingleByte      : True
    BodyName          : iso-8859-1
    EncodingName      : Western European (Windows)
    HeaderName        : Windows-1252
    WebName           : Windows-1252
    WindowsCodePage   : 1252
    IsBrowserDisplay  : True
    IsBrowserSave     : True
    IsMailNewsDisplay : True
    IsMailNewsSave    : True
    EncoderFallback   : System.Text.InternalEncoderBestFitFallback
    DecoderFallback   : System.Text.InternalDecoderBestFitFallback
    IsReadOnly        : True
    CodePage          : 1252
    
    >chcp 850
    Active code page: 850
    
    >chcp
    Active code page: 850
    
    >powershell -Command [console]::OutputEncoding
    
    IsSingleByte      : True
    BodyName          : ibm850
    EncodingName      : Western European (DOS)
    HeaderName        : ibm850
    WebName           : ibm850
    WindowsCodePage   : 1252
    IsBrowserDisplay  : False
    IsBrowserSave     : False
    IsMailNewsDisplay : False
    IsMailNewsSave    : False
    EncoderFallback   : System.Text.InternalEncoderBestFitFallback
    DecoderFallback   : System.Text.InternalDecoderBestFitFallback
    IsReadOnly        : True
    CodePage          : 850

Unfortunately, I couldn't find a result that has period at tail.

The reason why --use-setuprc option calls cp2utf8, please refer commit of e267ae7.

**Comment by kou1okada** [comment]
O.K.
I fixed it at 1ba7c33ae89d776948cb45059b73fdf002fc8af3.

Thanks.

**Comment by MAnantharaman** [comment]
Thanks - works for me:satisfied:
