### ISSUE TITLE
Adding bash autocompletion file

### ISSUE THREAD

**Issue by beevatsyu** [kou1okada/apt-cyg#18]
It would be fancier to have bash autocompetion file for apt-cyg.

**Comment by kou1okada** [comment]
Try `completion-install` subcommand.

**Comment by beevatsyu** [comment]
Sorry! Didn't see this subcommand. Keep the good work going! Thanks a lot!

**Comment by grant-humphries** [comment]
The completion feature is running very slowly for me, any tips to speed it up?
