### ISSUE TITLE
apt-cyg hangs

### ISSUE THREAD

**Issue by silviuvulcan** [kou1okada/apt-cyg#22]
Hi,

I recently did a dist-upgrade and ever since apt-cyg hangs and I can't seem to understand why. Almost all comands hang without output. 

What I did:

* update all cygwin packages using setup 
* update apt-cyg using git reset --hard, git pull

Debug (I ran using bash -x)

````
+ TRUSTEDKEYS=(CYGWIN CYGWINPORTS)
+ TRUSTEDKEY_CYGWIN_SUM=e6630b94e6bf1afcc1b1054afa9994a423764d795b2a3a5e831fc658962905dcadf63c3a29155136f3138d6375176c9384de68d12a6dd4dde35b55c9b225cd7f
+ TRUSTEDKEY_CYGWIN_FPR=1169DF9F22734F743AA59232A9A262FF676041BA
+ TRUSTEDKEY_CYGWIN_URL_LATEST=https://cygwin.com/key/pubring.asc
+ TRUSTEDKEY_CYGWINPORTS_SUM=ccf174d1e6ec20e50ff954e3d4a0c3de478032a100d26789c0190587ae80128e842ff5404ed3b48f8693c8803c88a3acbf8dca339edfdaab0f3c247fb6091e42
+ TRUSTEDKEY_CYGWINPORTS_FPR=45600BB98CA878AA97A70119FF20AF9A66EE1F94
+ TRUSTEDKEY_CYGWINPORTS_URL_LATEST=http://cygwinports.org/ports.gpg
+ ((  5 <= 0  ))
++ which wget
+ WGET=/usr/bin/wget
++ which tar
+ TAR=/usr/bin/tar
++ which awk
+ GAWK=/usr/bin/awk
++ which gpgv
+ GPGV=/usr/bin/gpgv
++ which gpg
+ GPG=/usr/bin/gpg
+ '[' -z /usr/bin/wget -o -z /usr/bin/tar -o -z /usr/bin/awk ']'
+ PACKAGE_DB=/etc/setup/installed.db
+ PACKAGEOF_CACHE=/tmp/.apt-cyg-packageof.cache.gz
+ PROGRESS_CHAR=("=" "-" "/" "|" "\\")
+ LESSER_PARALLEL_MAX_JOBS=8
+ noscripts=0
+ OPT_USER_PICKED=1
+ noupdate=0
+ OPT_FILES=()
+ SUBCOMMAND=
+ ignore_case=
+ force_remove=
+ force_fetch_trustedkeys=
+ no_verify=
+ OPT_PROXY=auto
+ OPT_PROXY_REFRESH_INTERVAL=86400
+ OPTS4INHERIT=()
++ current_cygarch
++ arch
++ sed -e 's/^i686$/x86/g'
+ SETUP_EXE=setup-x86_64.exe
+ YES_TO_ALL=false
+ INITIAL_ARGS=("$@")
+ ARGS=()
+ parse_args update
+ local unknown_option END_OPTS
+ '[' 1 -gt 0 ']'
+ case "$1" in
+ '[' -z '' ']'
+ SUBCOMMAND=update
+ shift
+ '[' 0 -gt 0 ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' 0 -gt 0 ']'
+ : 1
+ '[' -n '' ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' -z /usr/bin/gpgv -a -z '' ']'
+ wget --help
+ grep -- --show-progress
+ HAVE_SHOW_PROGRESS=--show-progress
+ wget --help
+ grep -- --no-verbose
+ HAVE_NO_VERBOSE=--no-verbose
+ ((  1 < 0  ))
+ ((  1 < 1  ))
+ ((  1 < 2  ))
+ WGET+=($HAVE_NO_VERBOSE $HAVE_SHOW_PROGRESS)
++ verbosefor 0
++ ((  1 < 0  ))
++ echo /dev/stderr
+ verbosefor0=/dev/stderr
++ verbosefor 1
++ ((  1 < 1  ))
++ echo /dev/stderr
+ verbosefor1=/dev/stderr
++ verbosefor 2
++ ((  1 < 2  ))
++ echo /dev/null
+ verbosefor2=/dev/null
++ verbosefor 3
++ ((  1 < 3  ))
++ echo /dev/null
+ verbosefor3=/dev/null
++ verbosefor 4
++ ((  1 < 4  ))
++ echo /dev/null
+ verbosefor4=/dev/null
++ verbosefor 5
++ ((  1 < 5  ))
++ echo /dev/null
+ verbosefor5=/dev/null
+ '[' -n '' ']'
++ which apt-cyg
+ SCRIPT_PATH=/usr/local/bin/apt-cyg
+ SCRIPT_FILE=apt-cyg
+ SCRIPT_NAME=apt-cyg
+ SCRIPT_DIR=/usr/local/bin
+++ which apt-cyg
++ realpath /usr/local/bin/apt-cyg
+ SCRIPT_REALPATH=/usr/local/src/apt-cyg/apt-cyg
+ SCRIPT_REALFILE=apt-cyg
+ SCRIPT_REALNAME=apt-cyg
+ SCRIPT_REALDIR=/usr/local/src/apt-cyg
+ proxy_setup
+ case "$OPT_PROXY" in
+ proxy_auto
++ ipconfig
++ md5sum -b
++ awk '{print $1}'
+ local hash=431f8323bb58d73ca1aa5f51dedfacf0
+ local cache=/tmp/apt-cyg.proxy.431f8323bb58d73ca1aa5f51dedfacf0
++ stat -c %Y /tmp/apt-cyg.proxy.431f8323bb58d73ca1aa5f51dedfacf0
+ local last=
++ date +%s
+ local now=1496129676
+ local proxy
+ '[' -n '' ']'
+ ((  (now - 0) < OPT_PROXY_REFRESH_INTERVAL  ))
++ /usr/bin/wget --no-verbose --show-progress --no-proxy -q -O - wpad/wpad.dat
++ grep PROXY
++ sed -e 's/^.*PROXY\s*\([^"]*\).*$/http:\/\/\1/g'
````

**Comment by kou1okada** [comment]
Thanks for reporting a problem.

But, hmm,,, I'm sorry.
It seems that PROXY auto-detection mechanism with [WPAD](https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol) missed to detect the PROXY.
The full set version of WPAD needs JavaScript, but the current implementation does not have it.
It's implemented to be simplified by string search for finding PROXY URL.
So, it can not be resolve the any logic to select PROXYs.

I suggest two temporary solutions as below:
1. Disable the PROXY auto-detection, if your network environment does not need PROXY.
2. Set a PROXY manually, if your network environment needs PROXY.

You can use `-p` option or `APT_CYG_PROXY` environment variable, to configure these settings.
For details, see [PROXY support](https://github.com/kou1okada/apt-cyg#proxy-support) section in the `README.md`.

**Comment by silviuvulcan** [comment]
Yes, that was it.

Setting 

    export APT_CYG_PROXY=none

fixes the issue. Weird, didn't change anything proxy related in while...

Thank you!

**Comment by kou1okada** [comment]
You can see the WPAD script in your environment by below command:

    wget --no-verbose --no-proxy -q -O - wpad/wpad.dat

Check it up, if you feel weird.

**Comment by silviuvulcan** [comment]
Just an emtpy line...

````
$ wget --no-verbose --no-proxy -q -O - wpad/wpad.dat

$
````

**Comment by kou1okada** [comment]
How about below command: (-q option is replaced by -v option)

    wget --no-verbose --no-proxy -v -O - wpad/wpad.dat

If your environment does not have the WPAD server, you will see result as below:

    --2017-06-07 16:49:40--  http://wpad/wpad.dat
    Resolving wpad... failed: Name or service not known.
    wget: unable to resolve host address ‘wpad’

Otherwise, if your environment has the WPAD server but the WPAD script is not supplied, you will see result as below:

    --2017-06-07 16:52:07--  wpad/wpad.dat
    Resolving wpad... xxx.xxx.xxx.xxx
    Connecting to wpad|xxx.xxx.xxx.xxx|:80... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2017-06-07 16:52:07 ERROR 404: Not Found.
    ...

**Comment by silviuvulcan** [comment]
No wapd:

````
 wget --no-verbose --no-proxy -v -O - wpad/wpad.dat
--2017-06-07 11:01:43--  http://wpad/wpad.dat
Resolving wpad... failed: Name or service not known.
wget: unable to resolve host address ‘wpad’
````

To add insult, since exporting proxy none I was able to run dist-upgrade again and my issue went away. (I ensured APT_CYG_PROXY is not set anymore)

**Comment by kou1okada** [comment]
Hmm,,,
I guess that when you had the problem, your environment has the WPAD server and the WPAD script, maybe...
But now, it doesn't have it, certainly.

Thanks.
