### ISSUE TITLE
Question: Any reason to use non-standard placeholder formatting?

### ISSUE THREAD

**Issue by E3V3A** [kou1okada/apt-cyg#30]
@kou1okada 
I really like the new formatting for the "help" options, but I am wondering why you prefer to use the non-standard way for showing place holders? 

The standard for most *help* or *usage* is to use **`<blahblah>`** for placeholders and **`[<options>]`** for  optional *options*. But you want to use `SOMETHING` which is commonly used for designating *constants*, in most languages including BASH. 

```
install PACKAGE_NAMES` |  to install packages 
```

Why?

**Comment by kou1okada** [comment]
I don't think so.
It is not non-standard style, but it's traditional UNIX style.
For examples, we can see it in the manpage of UNIX like system as [grep](http://manpages.ubuntu.com/manpages/bionic/en/man1/grep.1.html), [ls](http://manpages.ubuntu.com/manpages/bionic/en/man1/ls.1.html), [sort](http://manpages.ubuntu.com/manpages/bionic/en/man1/sort.1.html) and many other commands as below:
```
grep [OPTIONS] PATTERN [FILE...]
```
Maybe the style, which you are shown, is the standard one at Microsoft.
And we can see it in reference manuals of Microsoft at [cmd](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd), [copy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/copy), [dir](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir) and many other commands.
But in a recent case, [git](http://manpages.ubuntu.com/manpages/bionic/en/man1/git.1.html) adopts a similar style which you showed.
And, [apt-get](http://manpages.ubuntu.com/manpages/bionic/en/man8/apt-get.8.html) seems to adopt an intermediate style.

Hmm,,,
O.K.
I'll reconsider about placeholders style.

Currently, I feel the following rules to be reasonable.

|Style |Description|
|:---  |:-----------|
|something|Fixed string|
|\<something\>|Placeholder|
|[something]|Optional|
|{foo\|bar\|...}|Choose one of them|
|...|Previous element can repeatable|
