### ISSUE TITLE
apt-cyg describe gives wildcard results

### ISSUE THREAD

**Issue by E3V3A** [kou1okada/apt-cyg#33]
When I do (for example):
```bash
apt-cyg -X -u describe python3-devel
```
I also get details for `libboost_python3-devel`. This is undesired behavior.

**Comment by kou1okada** [comment]
Yes, I know it.
This behavior is inherited from original apt-cyg.
O.K.
I'll reconsider it.

**Comment by E3V3A** [comment]
Yeah, I was also trying to parse the output to only get the `ldesc`, `requires` and `depends`, but it turned ugly as your script is already bash and piping bash scripts taking a lot of options to output to more bash is asking for trouble.

**Comment by kou1okada** [comment]
That script is little bits strange.
Maybe the task you want to do is as below:
```
 apt-cyg -u -X -q describe '^libgdk_pixbuf2.0_0$' | sed -E '/^\[prev\]$/,$d;/^(install|source): *.+/d'
```

**Comment by E3V3A** [comment]
That's it! Can we implement it?

**Comment by E3V3A** [comment]
bump

**Comment by kou1okada** [comment]
Who are we?
I or you?

**Comment by E3V3A** [comment]
Hi! :) 
I think this time it's you. Because you know the code better than I, and suggested the improved regex. 
:+1:
