### ISSUE TITLE
New command - findall

### ISSUE THREAD

**Issue by sukucorp** [kou1okada/apt-cyg#38]
Hello,

I have added a new command findall which lists all packages available in setup.ini. Patch is as follows:

--- apt-cyg	2019-01-11 17:59:14.765675100 +0530
+++ apt-cyg-mod	2019-01-16 10:28:18.448664400 +0530
@@ -77,6 +77,7 @@
 	  update                   : to update setup.ini
 	  show                     : to show installed packages
 	  find <patterns> ...      : to find packages matching patterns
+	  findall                  : to find all packages
 	  describe <patterns> ...  : to describe packages matching patterns
 	  packageof <command or file names> ... :
 	                             to locate parent packages
@@ -924,7 +925,7 @@
   subcmd="\$( "\${getsubcmd[@]}" )"
   
   case "\$subcmd" in
-    install|depends|rdepends|describe|find)
+    install|depends|rdepends|describe|find|findall)
       COMPREPLY=( \$(awk '/^@ /{print \$2}' "$(apt-cyg pathof setup.ini)") )
       ;;
     remove)
@@ -1842,6 +1843,17 @@
 }
 
 
+function apt-cyg-findall ()
+{
+  findworkspace
+  getsetup
+  
+  echo ""
+  echo "Searching for all available packages:"
+  sed '1,/^setup-version:/d' setup.ini | awk 'BEGIN{RS="\n@ "; FS="\n"; ORS="\n"} {{print $1}}'
+}
+
+
 function apt-cyg-describe ()
 {
   local pkg

**Comment by kou1okada** [comment]
Thank you for posting a nice patch.
I will comment on three points.

First, please use [triple backticks](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) to paste patch code.
And perhaps `pull request` is better than `issue` in this case.

Second, maybe it can be substituted by `apt-cyg find .` (find subcommand with `.` pattern).
`.` means match any character in regular expressions.
So you can list up all packages by `apt-cyg find .` command.

Third, line [927](https://github.com/kou1okada/apt-cyg/blob/a7759e5a5e3600b0f24aa80386ae0a7b55e81bf9/apt-cyg#L927) is for bash completion.
And your findall subcommand seems that does not take any parameters, but your patch try to complete a parameter with a package name.

Thanks.

**Comment by sukucorp** [comment]
I didn't try the find . option, thanks for pointing it out. In that case, patch is not needed, will close the issue. Will create a pull request next time, since this was a minor change in code, did not create a branch.
