### ISSUE TITLE
Avoid domain user lookups

### ISSUE THREAD

**Issue by ilatypov** [kou1okada/apt-cyg#39]
I remember my tar invokations took inordinate amount of time because Cygwin's user lookup would go on and search for the user name by the ID in the Active Directory for each entry of a tar ball.  Perhaps using `tar --numeric-owner` could speed things up.

**Comment by kou1okada** [comment]
Thank you for valid advice for my fork.

I added `--numeric-owner` option to issue-39 branch.

Can you review performance improvement about https://github.com/kou1okada/apt-cyg/commit/4498ecacde09839c7df3b9546393a751c7057e12 on issue-39 branch ?

I measured performance by below commands:
```
# Prepare a package to measure performance
# Currently, cygwin-doc has 12 folders and 956 files.
# If this package is not enough to measure performance,
# please choose another one which is enough to measure performance.
pkg=cygwin-doc

# Cache a $pkg package to cygwin cache folder
apt-cyg remove $pkg 
apt-cyg install $pkg

# Prepare branches
git clone https://github.com/kou1okada/apt-cyg -b master /tmp/apt-cyg-master
git clone https://github.com/kou1okada/apt-cyg -b issue-39 /tmp/apt-cyg-issue-39
```

```
# Measure performance without this patch
apt-cyg remove $pkg
time /tmp/apt-cyg-master/apt-cyg -u install $pkg

# Measure performance with this patch
apt-cyg remove $pkg
time /tmp/apt-cyg-issue-39/apt-cyg -u install $pkg
```

A result on my environment (sorry, I have no environment with Active Directory) was below:
```
$ time /tmp/apt-cyg-master/apt-cyg -u install $pkg
...
real    0m5.693s
user    0m0.761s
sys     0m1.796s

$ time /tmp/apt-cyg-issue-39/apt-cyg -u install $pkg
...
real    0m5.598s
user    0m0.669s
sys     0m1.408s
```

Best regard.

**Comment by ilatypov** [comment]
The delay in a single tar xvf would measure as noticeable seconds when the tarball has a user ID not present in `/etc/passwd` and `net users /domains` shows thousands users. I forgot the exact mechanism Cygwin relies on in resolving user ID and whether it is configurable.

**Comment by ilatypov** [comment]
The delay in a single `tar xvf` would measure as noticeable seconds when the tarball has a user ID not present in `/etc/passwd` and `net users /domains` shows thousands users. I forgot the exact mechanism Cygwin relies on in resolving user ID and whether it is configurable.

**Comment by kou1okada** [comment]
Hmm, thanks.
I want to know the quantitative benefit of the performance.
And I hope there is no side effect.

**Comment by kou1okada** [comment]
4498ecacde09839c7df3b9546393a751c7057e12 was merged to master.
