### ISSUE TITLE
Could not download publickey

### ISSUE THREAD

**Issue by KoalasBruder** [kou1okada/apt-cyg#41]
I just installed apt-cyg on a fresh installation of cygwin but now it cannot download the publickey.
But I can go to that url in my browser and it resolves
Log:
```
Cache directory is /setup
Mirror is http://ftp.jaist.ac.jp/pub/cygwin
/tmp/tmp.3qu9rodpCA: No such file or directory
TRUSTEDKEY_CYGWIN: FAILED: Could not download https://cygwin.com/key/pubring.asc.
Error: Could not download TRUSTEDKEY_CYGWIN.
```

**Comment by kou1okada** [comment]
https://cygwin.com/key/pubring.asc is alive.
Your log shows that `wget` could not open temporary file `/tmp/tmp.3qu9rodpCA`.
It should have failed at https://github.com/kou1okada/apt-cyg/blob/be081f2d5f6f25ab9e136bd766b4e20d6f6b6a6e/apt-cyg#L484.

Would you check and report your environment by the result of following commands, please?
```
ls -ld /tmp
which wget
ldd "$(which wget)"
wget --version
wget -O /tmp/tmp.3qu9rodpCA https://cygwin.com/key/pubring.asc
ls -l /tmp/tmp.3qu9rodpCA
```
Note that you should replace `/tmp/tmp.3qu9rodpCA` to the temporary file which reported on the log.

**Comment by KoalasBruder** [comment]
Thanks for those steps.
The problem was that wget was from windows in my path.
After installing it from cygwin it works.
