### ISSUE TITLE
How to install apt-cyg to /usr/local/bin

### ISSUE THREAD

**Issue by Kaos-Industries** [kou1okada/apt-cyg#45]
I realised that when installing apt-cyg, I had installed it to my home directory without realising, simply creating a symbolic link to it in `/usr/local/bin` by following the instructions. However, in keeping with the philosophy of all software I install without a package manager, I'm trying to install apt-cyg directly to `/usr/local/bin`. 

However, when I do:

```
cd /usr/local/bin &&
git clone https://github.com/kou1okada/apt-cyg.git &&
ln -s "$(realpath apt-cyg)" /usr/local/bin/
```

...I get the error:

[ln: failed to create symbolic link '/usr/local/bin/apt-cyg': File exists](url)

However, even without doing `ln`, I'm still unable to run `apt-cyg`. Any idea what's going on here?

**Comment by kou1okada** [comment]
If you do following:
```
cd /usr/local/bin &&
git clone https://github.com/kou1okada/apt-cyg.git 
```
It clones `https://github.com/kou1okada/apt-cyg.git` to `/usr/local/bin/apt-cyg/`.
So you can't create symbolic link `/usr/local/bin/apt-cyg`, it is already directory.

And following is wrong too:
```
ln -s "$(realpath apt-cyg)" /usr/local/bin/
```
In this case, your working directory is `/usr/local/bin`.
Thus, the result of `$(realpath apt-cyg)` is `/usr/local/bin/apt-cyg`.
So `ln` try to make symbolic link for `/usr/local/bin/apt-cyg` -> `/usr/local/bin/apt-cyg`.
It seems like [Ouroboros](https://en.wikipedia.org/wiki/Ouroboros).
![Ouroboros](https://upload.wikimedia.org/wikipedia/commons/f/fa/Ouroboros.png)

**Comment by kou1okada** [comment]
Directories, which I recommend for the base of `git clone`, are `/usr/local`, `/usr/local/src`, `/usr/local/src/github.com/kou1okada`, `/opt`, `/opt/github.com/kou1okada`, etc,,,.

Maybe `/usr/local/src/github.com/kou1okada` is the best in this case.

Try this one:
```
DIR=/usr/local/src/github.com/kou1okada
mkdir -p "$DIR"
cd "$DIR"
git clone https://github.com/kou1okada/apt-cyg.git
ln -s "$(realpath apt-cyg/apt-cyg)" /usr/local/bin/
```

**Comment by Kaos-Industries** [comment]
> 
> 
> Directories, which I recommend for the base of `git clone`, are `/usr/local`, `/usr/local/src`, `/usr/local/src/github.com/kou1okada`, `/opt`, `/opt/github.com/kou1okada`, etc,,,.
> 
> Maybe `/usr/local/src/github.com/kou1okada` is the best in this case.
> 
> Try this one:
> 
> ```
> DIR=/usr/local/src/github.com/kou1okada
> mkdir -p "$DIR"
> cd "$DIR"
> git clone https://github.com/kou1okada/apt-cyg.git
> ln -s "$(realpath apt-cyg/apt-cyg)" /usr/local/bin/
> ```

I understand that, but this should mean that because apt-cyg is in usr/local/bin already, I don't need to make a symbolic link anyway, and apt-cyg should work, right? But as I mentioned in my OP, running apt-cyg still doesn't work, even when it is in /usr/local/bin and usr/local/bin is in the PATH.

**Comment by Kaos-Industries** [comment]
> 
> 
> Directories, which I recommend for the base of `git clone`, are `/usr/local`, `/usr/local/src`, `/usr/local/src/github.com/kou1okada`, `/opt`, `/opt/github.com/kou1okada`, etc,,,.
> 
> Maybe `/usr/local/src/github.com/kou1okada` is the best in this case.
> 
> Try this one:
> 
> ```
> DIR=/usr/local/src/github.com/kou1okada
> mkdir -p "$DIR"
> cd "$DIR"
> git clone https://github.com/kou1okada/apt-cyg.git
> ln -s "$(realpath apt-cyg/apt-cyg)" /usr/local/bin/
> ```
> 
> Note that if you already have `/usr/local/bin/apt-cyg`, don't forget to remove it before running above commands.
> 
> ```
> rm -rvfi /usr/local/bin/apt-cyg
> ```

So are you saying that it's impossible to make `apt-cyg` work in `usr/local/bin`?

**Comment by kou1okada** [comment]
Why you want to make a repository on `/usr/local/bin`?
I repeat to say that following commands do not make a script `/usr/local/bin/apt-cyg` but a directory.
```
cd /usr/local/bin &&
git clone https://github.com/kou1okada/apt-cyg.git 
```
The script file is `/usr/local/bin/apt-cyg/apt-cyg`.
And your PATH have not `/usr/local/bin/apt-cyg` but `/usr/local/bin`.

**Comment by Kaos-Industries** [comment]
> 
> 
> Why you want to make a repository on `/usr/local/bin`?
> I repeat to say that following commands do not make a script `/usr/local/bin/apt-cyg` but a directory.
> 
> ```
> cd /usr/local/bin &&
> git clone https://github.com/kou1okada/apt-cyg.git 
> ```
> 
> The script file is `/usr/local/bin/apt-cyg/apt-cyg`.
> And your PATH have not `/usr/local/bin/apt-cyg` but `/usr/local/bin`.

Okay, I understand what you're saying now. How about this:

```
cd /usr/local/src
git clone https://github.com/kou1okada/apt-cyg.git &&
ln -s "$(realpath ./apt-cyg)" /usr/local/bin/
```

**Comment by kou1okada** [comment]
No.
```
ln -s "$(realpath ./apt-cyg)" /usr/local/bin/
```
The result of `$(realpath ./apt-cyg)` is `/usr/local/src/apt-cyg`.
It's directory.
The script, that you want to run, is `/usr/local/src/apt-cyg/apt-cyg`.

The sequence of commands that you really wanted to do is following:
```
DIR=/usr/local/src
mkdir -p "$DIR"
cd "$DIR"
git clone https://github.com/kou1okada/apt-cyg.git
ln -s "$(realpath apt-cyg/apt-cyg)" /usr/local/bin/
```

**Comment by Kaos-Industries** [comment]
> 
> 
> No.
> 
> ```
> ln -s "$(realpath ./apt-cyg)" /usr/local/bin/
> ```
> 
> The result of `$(realpath ./apt-cyg)` is `/usr/local/src/apt-cyg`.
> It's directory.
> The script, that you want to run, is `/usr/local/src/apt-cyg/apt-cyg`.
> 
> The sequence of commands that you really wanted to do is following:
> 
> ```
> DIR=/usr/local/src
> mkdir -p "$DIR"
> cd "$DIR"
> git clone https://github.com/kou1okada/apt-cyg.git
> ln -s "$(realpath apt-cyg/apt-cyg)" /usr/local/bin/
> ```

My bad, the part that you saw/quoted was an old edit that I copied without udpating. I've edited it now, and that's what I was referring to.

**Comment by Kaos-Industries** [comment]
> 
> 
> It's O.K.
> But you should consider the case that your environment never have `/usr/local/src` yet.
> I recommend do `mkdir -p /usr/local/src` before you do it.

Yeah, Cygwin's doesn't come with /usr/local/src, it was the plan to make the directory first, I just wanted to make sure the rest of the commands were good. Thanks for your patient help once again.

**Comment by kou1okada** [comment]
Hmm,,,
`Edit` makes confusing.

**Comment by kou1okada** [comment]
If someone, who are reading this issue, is confused, please refer `edited` log too.

**Comment by alg2** [comment]
> cd /usr/local/bin &&
> git clone https://github.com/kou1okada/apt-cyg.git &&
> ln -s "$(realpath apt-cyg)" /usr/local/bin/

Your commands give the reason why:
When you cloned apt-cyg in /usr/local/bin, you created a directory "apt-cyg" in /usr/local/bin .
When you then tried to create the symlink  of the apt-cyg script (a file) to /usr/local/bin, it
failed because there's already a directory named "apt-cyg" .

I'd advise checking out any version control source into a dev dir underneath your $HOME dir, and simply install to the target /usr/local/bin/.   THis way, you don't pollute a  dir that should only contain executables.    I know this is cygwin, but it's a good practice, imho to separate the dev files from the prod/installation files.  It would work well whether you're in cygwin, msys, or any  *[iu]x  system.

**Comment by hoshsadiq** [comment]
Why not just download it directly? As an admin console, run the following:
```
curl -fsSL https://raw.githubusercontent.com/kou1okada/apt-cyg/master/apt-cyg -o /usr/local/bin/apt-cyg
chmod +x /usr/local/bin/apt-cyg
```

**Comment by kou1okada** [comment]
Because for enabling 'upgrade-self' subcommand.

**Comment by Kaos-Industries** [comment]
Coming back to this, I solved it by doing: 

cd /usr/local/bin
https://github.com/kou1okada/apt-cyg.git

...and then adding: 

`export PATH="$PATH:/usr/local/bin/apt-cyg"`

to my `~/.bash_profile`. 

This gives me the best of all worlds: have apt-cyg installed directly into the `/usr/local/bin` folder without needing to install it anywhere else or mess around with symbolic links, and put it under revision control to enable `upgrade-self`.

**Comment by kou1okada** [comment]
I repeat, my recommendation is https://github.com/kou1okada/apt-cyg/issues/45#issuecomment-481098110.
To make repository under `/usr/local/bin` is not standard, maybe.
Perhaps, the bast place to make a repository is under the `/opt` or `/usr/local/src`, I think.
[Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) on Wikipedia may help understanding it.

**Comment by Kaos-Industries** [comment]
Fair enough, but I'm trying to store apt-cyg somewhere where it's more easily accessible. How about my home directory, is that supported? I tried doing this, with a symlink to `/usr/local/bin` as the documentation suggests, but for some reason everytime I run apt-cyg it creates a separate `apt-cyg` and installation folder on my desktop instead of inside my home directory. I don't remember this behaviour occurring before, and I'd like to keep my desktop clear while keeping all of the apt-cyg stuff together in the home folder.

**Comment by kou1okada** [comment]
> How about my home directory, is that supported?

Of course, Yes.
You can install `apt-cyg` anywhere you want.

> I tried doing this, with a symlink to /usr/local/bin as the documentation suggests, but for some reason everytime I run apt-cyg it creates a separate apt-cyg and installation folder on my desktop instead of inside my home directory.

Perhaps, you downloaded `setup-x86_64.exe' to the DESKTOP and then executed it on the DESKTOP and installed cygwin.
Please check the location of the cache directory with following command:
```
apt-cyg pathof cache
```
Probably it will be "/cygdrive/c/Users/${USER}/Desktop" on your environment.

`apt-cyg set-cache <directory>` sub-command helps you to change it another location.

I'm using the default Downloads folder of Windows.
You can use it with following:
```
apt-cyg set-cache "$USERPROFILE/Downloads/cygwin"
```

**Comment by Kaos-Industries** [comment]
That worked perfectly, thank you.
