### ISSUE TITLE
problem with double cygwin install to different directory

### ISSUE THREAD

**Issue by kyvli** [kou1okada/apt-cyg#47]
when i install double cygwin to different directory, with different root-dir and different local-package-dir for test, then i found a problem, the output of apt-cyg dist-upgrade show that local-package-dir point to the same dir

then i modified line 1485 as :

local setup=( ".\\${SETUP_EXE}" -R "$(cygpath -wa /)" -B -q -n -g -l "$(cygpath -wa "$(apt-cyg-pathof cache)")" )

could resolve this problem, but why ?

sorry for my pool english.

**Comment by kou1okada** [comment]
Hmm, this problem, multiple installation of cygwin, is a little complexity.
I received this issue and read following source code of `setup.exe`:
https://sourceware.org/git/gitweb.cgi?p=cygwin-setup.git

It seems that setup.rc and root directory will be determined following steps:
1. Try to read "file://" + cwd + "/" + "setup.rc" at `UserSettings.cc` line [70-75](https://github.com/kou1okada/cygwin-setup/blob/424c621a19b52b10eeb7d8a5bafd44e059d80e17/UserSettings.cc#L70-L75).
2. If step 1 failed, then try to read "cygfile:///etc/setup/" + "setup.rc" at `UserSettings.cc` line [76-81](https://github.com/kou1okada/cygwin-setup/blob/424c621a19b52b10eeb7d8a5bafd44e059d80e17/UserSettings.cc#L76-L81). In this case, "cygfile:///" will be determined by [cygpath()](https://github.com/kou1okada/cygwin-setup/blob/424c621a19b52b10eeb7d8a5bafd44e059d80e17/mount.cc#L421-L448), but at this stage [set_root_dir()](https://github.com/kou1okada/cygwin-setup/blob/424c621a19b52b10eeb7d8a5bafd44e059d80e17/mount.cc#L375-L379) has been never called. So [read_mounts(std::string())](https://github.com/kou1okada/cygwin-setup/blob/424c621a19b52b10eeb7d8a5bafd44e059d80e17/io_stream_cygfile.cc#L120) determines rootdir with `HKEY_LOCAL_MACHINE\SOFTWARE\cygwin\setup\rootdir` or `HKEY_CURRENT_USER\Software\cygwin\setup\rootdir` at `mount.cc` line [330-360](https://github.com/kou1okada/cygwin-setup/blob/424c621a19b52b10eeb7d8a5bafd44e059d80e17/mount.cc#L330-L360). Note that `HKEY_LOCAL_MACHINE` takes priority.
3. When `Cygwin setup - Choose Installation Directory` dialog displayed, it will determine initial value for `root directory` with `--root` option or `HKEY_LOCAL_MACHINE\SOFTWARE\cygwin\setup\rootdir` or `HKEY_CURRENT_USER\Software\cygwin\setup\rootdir` at `root.cc` line [260-260](https://github.com/kou1okada/cygwin-setup/blob/424c621a19b52b10eeb7d8a5bafd44e059d80e17/root.cc#L260-L269). But this will be not use for read for `setup.rc`.

As you can see in the above steps, `setup.rc` seems to be read only once at step 1 or 2 before root directory is determined at step 3.
This should make some troubles in the case as multiple installation of cygwin.

Even more unfortunately the current version of `setup.exe` has no command line options for giving the location of `setup.rc`.

Perhaps, the means for giving `setup.rc` to `setup.exe`, which we can take, is following, maybe:
* Prepare `./setup.rc` in the same directory as `setup.exe`.
* Rewrite `HKEY_LOCAL_MACHINE\SOFTWARE\cygwin\setup\rootdir` or `HKEY_CURRENT_USER\Software\cygwin\setup\rootdir`.

**Comment by kou1okada** [comment]
Please check above commit c3b4d00 on issue-47 branch.

**Comment by kou1okada** [comment]
I updated [issue-47 branch](https://github.com/kou1okada/apt-cyg/tree/issue-47) with 305947b32ba38160a4463d304dce4965d6622771.
Can you try it?
