### ISSUE TITLE
apt-cyg showinfo <package names>

### ISSUE THREAD

**Issue by sukucorp** [kou1okada/apt-cyg#49]
Attaching a patch from the original apt-cyg that will show package description for the given packages.

```
--- /usr/local/bin/apt-cyg	2019-06-05 10:09:57.519749400 +0530
+++ apt-cyg	2019-06-05 17:56:32.650265400 +0530
@@ -188,6 +188,8 @@
 	  key-list                 : to list keys
 	  key-finger               : to list fingerprints
 	  upgrade-self             : to upgrade apt-cyg
+	  showinfo <package names> ... :
+	                             to show description for packages
 	  depends <package names> ... :
 	                             to show forward dependency information
 	                             for packages with depth.
@@ -1233,7 +1235,7 @@
   subcmd="$( "${getsubcmd[@]}" )"
   
   case "$subcmd" in
-    install|depends|rdepends|describe|find)
+    install|depends|rdepends|describe|find|showinfo)
       COMPREPLY=( $(awk '/^@ /{print $2}' "$(apt-cyg pathof setup.ini)") )
       ;;
     remove)
@@ -2192,6 +2194,28 @@
   done
 }
 
+function apt-cyg-showinfo ()
+{
+  local pkg
+  
+  checkpackages "$@"
+  findworkspace
+  getsetup
+  for pkg do
+    (( notfirst++ )) && echo
+    awk '
+    $1 == query {
+      print
+      fd++
+    }
+    END {
+      if (! fd)
+      print "Unable to locate package " query
+    }
+    ' RS='\n\n@ ' FS='\n' query="$pkg" setup.ini
+  done
+}
+
 function apt-cyg-packageof ()
 {
   if [ -z "$OPT_AG" ]; then

```

**Comment by kou1okada** [comment]
Did you try `describe` subcommand?
I think that it is almost same as your patch except using regular expression.
See below:
https://github.com/kou1okada/apt-cyg/blob/eacd9ee86cc3fe33f3cc0f2935d211da80e496c3/apt-cyg#L2180-L2193

And maybe issue #33 is a tip related to this issue.

**Comment by sukucorp** [comment]
In am currently using the same syntax as issue #33 to find info on a package, but thought it would be easier to just use the package name directly instead of regex. I will leave it up to you whether to incorporate the change.

On a related note, I am planning to create a patch for "apt-cyg category" function from the original apt-cyg.

**Comment by kou1okada** [comment]
Hmm.
It is desirable that the function will be provided by a command line option rather than individual subcommand, I felt.
Like below:
```
apt-cyg describe <package name>
apt-cyg describe -E <pattern for package name>
```

**Comment by sukucorp** [comment]
Yes, that would be cleaner.

**Comment by sukucorp** [comment]
Is the pattern matching option required for apt-cyg describe? Normally users will first search for a package name using find and then only use describe when they need additional information on the package.

**Comment by kou1okada** [comment]
I checked behaviors of `apt-cache show`.
`apt-cache show "gcc"` matched only "gcc".
`apt-cache show "gcc."` matched any packages which seem to have name matching regular expression /gcc./.
`apt-cache show "gcc-(5|6)"` matched any packages which seem to have name matching regular expression /gcc-(5|6)/.
`apt-cache show "gcc-[56]"` matched only gcc-5 and gcc-6.
`apt-cache show gcc-` did not match any packages.
Hmm,,,

**Comment by kou1okada** [comment]
How do you think above patch?

**Comment by sukucorp** [comment]
Awesome!

**Comment by sukucorp** [comment]
Change can be merged back to trunk.

**Comment by sukucorp** [comment]
"apt-cyg describe libMagickC++6_8" does not produce any output. It works with the initial patch I had submitted.
