### ISSUE TITLE
Use -o /dev/null for wget invocation

### ISSUE THREAD

**Issue by sukucorp** [kou1okada/apt-cyg#52]
wget.log file is created when apt-cyg is run. To disable this wget -o /dev/null should be used.

**Comment by kou1okada** [comment]
I wonder why your environment outputs "wget.log", my environment does not.
I think that `wget` does not automatically output "wget.log" except `-b` or `-o` options are set, maybe.
Additionally I have never used both options in apt-cyg.
And default filename by `-b` option is not "wget.log" but "wget-log".

Are  you using `logfile` command in wgetrc on your environment, by any chance?
Please check `/etc/wgetrc` and `~/.wgetrc`.

**Comment by sukucorp** [comment]
I have the default /etc/wgetrc, no ~/.wgetrc and no envar set related to wget.
Might be a false report, the file is in the same directory from where I use apt-cyg but is a month old. So might have been created when I would have invoked wget manually.
