### ISSUE TITLE
 Was the category subcommand removed?

### ISSUE THREAD

**Issue by Kaos-Industries** [kou1okada/apt-cyg#65]
I just downloaded the latest version of apt-cyg, and I noticed that `category` is listed as a subcategory:

```
category <category>      : List all packages in given <category>.
```

but trying to use it results in the following error:

```
$ apt-cyg category games
cat: '': No such file or directory
```

I then looked at README.md, and sure enough it seems that the category subcommand is not in there. Was this feature removed from the program, and if so, why?

I was hoping to be able to use it to remove all installed packages of a given category, maybe with something like:

```
apt-cyg category games | apt-cyg remove
```

**Comment by kou1okada** [comment]
You just downloaded `apt-cyg`, but you never updated `setup.ini`, maybe.
Try following:
```
apt-cyg update
apt-cyg category games
```
If you still fail it, please report the result of below commands:
```
apt-cyg pathof setup.ini
ls -l "$(apt-cyg pathof setup.ini)"
```

In the case to uninstall all packages of a given category, try following:
```
apt-cyg category games | xargs apt-cyg remove
```

**Comment by Kaos-Industries** [comment]
This worked perfectly, thank you.
