### ISSUE TITLE
apt-cyg blocks from a missing cygwinports.org

### ISSUE THREAD

**Issue by MironVeryanskiy** [kou1okada/apt-cyg#67]
Due to http://cygwinports.org/ports.gpg being unavailble,
apt-cyg is blocked from performing operations that depend on it.
For example:
`apt-cyg pathof cache`
`apt-cyg update-setup`
Either hang, or timeout because of cygwinports.org.

https://github.com/kou1okada/apt-cyg/blob/d7ca0746af4748251ec67efbb99e02df3ce9284d/apt-cyg#L156

**Comment by kou1okada** [comment]
I was missing that http://cygwinports.org/ was no longer available.
Thanks.
