### ISSUE TITLE
The dependencies cannot be solved.

### ISSUE THREAD

**Issue by kou1okada** [kou1okada/apt-cyg#90]
@jarnosz reported this problem at issue #88 comment [1287576006](https://github.com/kou1okada/apt-cyg/issues/88#issuecomment-1287576006).

This is because the `requires:` field is gone from the `setup.ini`.
It seems that is replaced by `depends2:` field.
The `setup.ini` specifications may have changed.

```console
$ cat "$(apt-cyg pathof setup.ini)" | grep -Ei "^(requires|depend.*):" | awk '$0=$1' | sort | uniq -c
  23687 depends2:
```

**Comment by kou1okada** [comment]
Does anyone know of any upstream changes regarding this issue?

I suspected [cygport](https://cygwin.com/git/?p=cygwin-apps/cygport.git;a=summary), but  cygport 0.35.4 (the latest version) still generates `requires` field to .hint file.

**Comment by jarnosz** [comment]
patch seems to be working.
